name = "Max Bear"
license = "MIT"
licenselink = "https://github.com/themaxdavitt/hugo-maxbear/blob/master/LICENSE"
description = "A private theme based on Bear Cub for Max Davitt's personal website"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/themaxdavitt/hugo-maxbear"

# If you have a running demo of the theme.
demosite = "https://max.davitt.me"

# If the theme has a single author
[original]
  name = "Bear Cub"
  homepage = "https://github.com/clente/hugo-bearcub"
